<?php
// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

return [
    'title' => 'AI assistant',
    'caption' => 'Community help',
    'description' => 'Ask a question and the community assistant will reply. It can help you find your way around the platform.',
    'ai_notice' => 'Replies are generated by AI and may be inaccurate. Do not share sensitive personal information.',
    'conversations_title' => 'Your conversations',
    'new_conversation' => 'Start a new conversation',
    'no_conversations' => 'You have no conversations yet. Ask a question below to start one.',
    'thread_title' => 'Conversation',
    'empty_thread' => 'No messages yet. Ask a question to begin.',
    'message_label' => 'Your message',
    'message_hint' => 'Type your question, then select Send to get a reply.',
    'send' => 'Send',
    'you' => 'You',
    'assistant' => 'Assistant',
    'unavailable_reply' => 'Sorry, the assistant is unavailable right now. Please try again later.',
    'disabled_notice' => 'The AI assistant is not available at the moment.',
    'status_empty' => 'Enter a message to send.',
];
