module.exports = {
    // Content to scan for used classes
    content: [
        'views/**/*.php',
        'httpdocs/**/*.php',
        'httpdocs/assets/js/**/*.js',
        'src/**/*.php',
    ],

    // CSS files to purge
    // Auto-discovered: 2026-01-24
    //
    // ⚠️ IMPORTANT: Design token files are EXCLUDED from this list
    // They contain CSS variables that PurgeCSS incorrectly removes
    // See CSS_BUILD_RULES.md for details
    css: [
        'httpdocs/assets/css/accessibility.css',
        'httpdocs/assets/css/achievements.css',
        'httpdocs/assets/css/admin-federation.css',
        'httpdocs/assets/css/admin-gold-standard.css',
        'httpdocs/assets/css/admin-header.css',
        'httpdocs/assets/css/admin-menu-builder.css',
        'httpdocs/assets/css/admin-menu-index.css',
        'httpdocs/assets/css/admin-settings.css',
        'httpdocs/assets/css/admin-sidebar.css',
        'httpdocs/assets/css/ai-chat-widget.css',
        'httpdocs/assets/css/auth.css',
        'httpdocs/assets/css/avatar-placeholders.css',
        'httpdocs/assets/css/badge-animations.css',
        'httpdocs/assets/css/biometric-modal.css',
        'httpdocs/assets/css/blog-index.css',
        'httpdocs/assets/css/blog-show-temp.css',
        'httpdocs/assets/css/blog-show.css',
        'httpdocs/assets/css/branding.css',
        'httpdocs/assets/css/breakpoints.css',
        'httpdocs/assets/css/bundles/admin-core.css',
        'httpdocs/assets/css/bundles/admin-modules.css',
        'httpdocs/assets/css/bundles/civicone-core.css',
        'httpdocs/assets/css/bundles/civicone-govuk-all.css',
        'httpdocs/assets/css/bundles/civicone-modules.css',
        'httpdocs/assets/css/bundles/civicone-profile-all.css',
        'httpdocs/assets/css/bundles/civicone-utilities.css',
        'httpdocs/assets/css/bundles/components-buttons.css',
        'httpdocs/assets/css/bundles/components-cards.css',
        'httpdocs/assets/css/bundles/components-forms.css',
        'httpdocs/assets/css/bundles/components-modals.css',
        'httpdocs/assets/css/bundles/components-navigation.css',
        'httpdocs/assets/css/bundles/components-notifications.css',
        'httpdocs/assets/css/bundles/components.css',
        'httpdocs/assets/css/bundles/core-framework.css',
        'httpdocs/assets/css/bundles/core.css',
        'httpdocs/assets/css/bundles/enhancements.css',
        'httpdocs/assets/css/bundles/features-federation.css',
        'httpdocs/assets/css/bundles/features-gamification.css',
        'httpdocs/assets/css/bundles/features-pwa.css',
        'httpdocs/assets/css/bundles/features-social.css',
        'httpdocs/assets/css/bundles/mobile.css',
        'httpdocs/assets/css/bundles/modern-pages.css',
        'httpdocs/assets/css/bundles/polish.css',
        'httpdocs/assets/css/bundles/utilities-accessibility.css',
        'httpdocs/assets/css/bundles/utilities-loading.css',
        'httpdocs/assets/css/bundles/utilities-polish.css',
        'httpdocs/assets/css/button-ripple.css',
        'httpdocs/assets/css/card-hover-states.css',
        'httpdocs/assets/css/civicone-about-story.css',
        'httpdocs/assets/css/civicone-account-nav.css',
        'httpdocs/assets/css/civicone-achievement-showcase.css',
        'httpdocs/assets/css/civicone-achievements.css',
        'httpdocs/assets/css/civicone-ai-chat-widget.css',
        'httpdocs/assets/css/civicone-ai-index.css',
        'httpdocs/assets/css/civicone-auth-forms.css',
        'httpdocs/assets/css/civicone-auth-login.css',
        'httpdocs/assets/css/civicone-auth-register.css',
        'httpdocs/assets/css/civicone-auth.css',
        'httpdocs/assets/css/civicone-blog-utilities.css',
        'httpdocs/assets/css/civicone-blog.css',
        'httpdocs/assets/css/civicone-breadcrumb.css',
        'httpdocs/assets/css/civicone-bundle-compiled.css',
        'httpdocs/assets/css/civicone-compose.css',
        'httpdocs/assets/css/civicone-consent-decline.css',
        'httpdocs/assets/css/civicone-consent-required.css',
        'httpdocs/assets/css/civicone-contact.css',
        'httpdocs/assets/css/civicone/cookie-banner.css',
        'httpdocs/assets/css/civicone-dashboard-nexus-score.css',
        'httpdocs/assets/css/civicone-dashboard.css',
        'httpdocs/assets/css/civicone-demo-pages.css',
        'httpdocs/assets/css/civicone-dev-banner.css',
        'httpdocs/assets/css/civicone-directory-utilities.css',
        'httpdocs/assets/css/civicone-events-calendar.css',
        'httpdocs/assets/css/civicone-events-edit.css',
        'httpdocs/assets/css/civicone-events-show.css',
        'httpdocs/assets/css/civicone-events.css',
        'httpdocs/assets/css/civicone-faq.css',
        'httpdocs/assets/css/civicone-federation-shell.css',
        'httpdocs/assets/css/civicone-federation.css',
        'httpdocs/assets/css/civicone-feed-item.css',
        'httpdocs/assets/css/civicone-feed-show.css',
        'httpdocs/assets/css/civicone-feed.css',
        'httpdocs/assets/css/civicone-footer.css',
        'httpdocs/assets/css/civicone-goals-delete.css',
        'httpdocs/assets/css/civicone-goals-edit.css',
        'httpdocs/assets/css/civicone-goals-form.css',
        'httpdocs/assets/css/civicone-goals-show.css',
        'httpdocs/assets/css/civicone-govuk-buttons.css',
        'httpdocs/assets/css/civicone-govuk-components.css',
        'httpdocs/assets/css/civicone-govuk-content.css',
        'httpdocs/assets/css/civicone-govuk-feedback.css',
        'httpdocs/assets/css/civicone-govuk-focus.css',
        'httpdocs/assets/css/civicone-govuk-forms.css',
        'httpdocs/assets/css/civicone-govuk-navigation.css',
        'httpdocs/assets/css/civicone-govuk-spacing.css',
        'httpdocs/assets/css/civicone-govuk-tabs.css',
        'httpdocs/assets/css/civicone-govuk-typography.css',
        'httpdocs/assets/css/civicone-groups-create-overlay.css',
        'httpdocs/assets/css/civicone-groups-discussions-create.css',
        'httpdocs/assets/css/civicone-groups-discussions-show.css',
        'httpdocs/assets/css/civicone-groups-edit.css',
        'httpdocs/assets/css/civicone-groups-invite.css',
        'httpdocs/assets/css/civicone-groups-my-groups.css',
        'httpdocs/assets/css/civicone-groups-show.css',
        'httpdocs/assets/css/civicone-groups-utilities.css',
        'httpdocs/assets/css/civicone-groups.css',
        'httpdocs/assets/css/civicone-header-v2.css',
        'httpdocs/assets/css/civicone-help.css',
        'httpdocs/assets/css/civicone-home.css',
        'httpdocs/assets/css/civicone-how-it-works.css',
        'httpdocs/assets/css/civicone-impact-summary.css',
        'httpdocs/assets/css/civicone-impersonation-banner.css',
        'httpdocs/assets/css/civicone-layout-overrides.css',
        'httpdocs/assets/css/civicone-leaderboard.css',
        'httpdocs/assets/css/civicone-legal-hub.css',
        'httpdocs/assets/css/civicone-legal-volunteer-license.css',
        'httpdocs/assets/css/civicone-listings-directory.css',
        'httpdocs/assets/css/civicone-master-dashboard.css',
        'httpdocs/assets/css/civicone-master-edit-tenant.css',
        'httpdocs/assets/css/civicone-master-users.css',
        'httpdocs/assets/css/civicone-matches.css',
        'httpdocs/assets/css/civicone-members-directory-legacy-backup-2026-01-22.css',
        'httpdocs/assets/css/civicone-members-directory.css',
        'httpdocs/assets/css/civicone-messages-index.css',
        'httpdocs/assets/css/civicone-messages.css',
        'httpdocs/assets/css/civicone-mini-modules.css',
        'httpdocs/assets/css/civicone-mobile-about.css',
        'httpdocs/assets/css/civicone-mobile-nav-v2-inline.css',
        'httpdocs/assets/css/civicone-mobile-nav-v2.css',
        'httpdocs/assets/css/civicone-mobile.css',
        'httpdocs/assets/css/civicone-native.css',
        'httpdocs/assets/css/civicone-nexus-impact-report.css',
        'httpdocs/assets/css/civicone-nexus-leaderboard.css',
        'httpdocs/assets/css/civicone-nexus-score-charts.css',
        'httpdocs/assets/css/civicone-nexus-score-dashboard.css',
        'httpdocs/assets/css/civicone-nexus-score-widget.css',
        'httpdocs/assets/css/civicone-onboarding-index.css',
        'httpdocs/assets/css/civicone-org-ui-components.css',
        'httpdocs/assets/css/civicone-organizations-audit-log.css',
        'httpdocs/assets/css/civicone-organizations-members.css',
        'httpdocs/assets/css/civicone-organizations-transfer-requests.css',
        'httpdocs/assets/css/civicone-organizations-utility-bar.css',
        'httpdocs/assets/css/civicone-organizations-wallet.css',
        'httpdocs/assets/css/civicone-our-story.css',
        'httpdocs/assets/css/civicone-pages-legal.css',
        'httpdocs/assets/css/civicone-pages-our-story.css',
        'httpdocs/assets/css/civicone-pages-privacy.css',
        'httpdocs/assets/css/civicone-partner.css',
        'httpdocs/assets/css/civicone-polls-edit.css',
        'httpdocs/assets/css/civicone-polls-show.css',
        'httpdocs/assets/css/civicone-privacy.css',
        'httpdocs/assets/css/civicone-profile-edit.css',
        'httpdocs/assets/css/civicone-profile-header.css',
        'httpdocs/assets/css/civicone-profile-show.css',
        'httpdocs/assets/css/civicone-profile-social.css',
        'httpdocs/assets/css/civicone-profile.css',
        'httpdocs/assets/css/civicone-report-pages.css',
        'httpdocs/assets/css/civicone-resources-form.css',
        'httpdocs/assets/css/civicone-reviews-create.css',
        'httpdocs/assets/css/civicone-search-results.css',
        'httpdocs/assets/css/civicone-shared-accessibility-helpers.css',
        'httpdocs/assets/css/civicone-shared-post-card.css',
        'httpdocs/assets/css/civicone-skeleton-card.css',
        'httpdocs/assets/css/civicone-skeleton-feed.css',
        'httpdocs/assets/css/civicone-social-prescribing.css',
        'httpdocs/assets/css/civicone-timebanking-guide.css',
        'httpdocs/assets/css/civicone-utilities-extended.css',
        'httpdocs/assets/css/civicone-utilities.css',
        'httpdocs/assets/css/civicone-volunteering-certificate.css',
        'httpdocs/assets/css/civicone-volunteering-create-opp.css',
        'httpdocs/assets/css/civicone-volunteering-dashboard.css',
        'httpdocs/assets/css/civicone-volunteering-edit-opp.css',
        'httpdocs/assets/css/civicone-volunteering-edit-org.css',
        'httpdocs/assets/css/civicone-volunteering-my-applications.css',
        'httpdocs/assets/css/civicone-volunteering-organizations.css',
        'httpdocs/assets/css/civicone-volunteering-show-org.css',
        'httpdocs/assets/css/civicone-volunteering-show.css',
        'httpdocs/assets/css/civicone-volunteering.css',
        'httpdocs/assets/css/civicone-wallet-index.css',
        'httpdocs/assets/css/civicone-wallet.css',
        'httpdocs/assets/css/components.css',
        'httpdocs/assets/css/compose-multidraw.css',
        'httpdocs/assets/css/consent-required.css',
        'httpdocs/assets/css/cookie-banner.css',
        'httpdocs/assets/css/cookie-preferences.css',
        'httpdocs/assets/css/dashboard.css',
        // EXCLUDED: Design tokens should NEVER be purged - they contain CSS variables
        // 'httpdocs/assets/css/design-tokens.css',
        // 'httpdocs/assets/css/desktop-design-tokens.css',
        'httpdocs/assets/css/desktop-hover-system.css',
        'httpdocs/assets/css/desktop-loading-states.css',
        'httpdocs/assets/css/dev-notice-modal.css',
        'httpdocs/assets/css/empty-states.css',
        'httpdocs/assets/css/error-states.css',
        'httpdocs/assets/css/error-pages.css',
        'httpdocs/assets/css/events-calendar.css',
        'httpdocs/assets/css/events-create.css',
        'httpdocs/assets/css/events-index.css',
        'httpdocs/assets/css/events-show.css',
        'httpdocs/assets/css/fab-polish.css',
        'httpdocs/assets/css/federation-realtime.css',
        'httpdocs/assets/css/federation-reviews.css',
        'httpdocs/assets/css/federation.css',
        'httpdocs/assets/css/feed-action-pills.css',
        'httpdocs/assets/css/feed-empty-state.css',
        'httpdocs/assets/css/feed-filter.css',
        'httpdocs/assets/css/feed-item.css',
        'httpdocs/assets/css/feed-page.css',
        'httpdocs/assets/css/feed-show.css',
        'httpdocs/assets/css/focus-rings.css',
        'httpdocs/assets/css/form-validation.css',
        'httpdocs/assets/css/glass.css',
        'httpdocs/assets/css/goals.css',
        'httpdocs/assets/css/groups-edit-overlay.css',
        'httpdocs/assets/css/groups-show.css',
        'httpdocs/assets/css/groups.css',
        'httpdocs/assets/css/help.css',
        'httpdocs/assets/css/hover-interactions.css',
        'httpdocs/assets/css/image-lazy-load.css',
        'httpdocs/assets/css/layout-isolation.css',
        'httpdocs/assets/css/listings-create.css',
        'httpdocs/assets/css/listings-index.css',
        'httpdocs/assets/css/listings-show.css',
        'httpdocs/assets/css/loading-skeletons.css',
        'httpdocs/assets/css/master-dashboard.css',
        'httpdocs/assets/css/matches.css',
        'httpdocs/assets/css/mega-menu-icons.css',
        'httpdocs/assets/css/members-directory-v1.6.css',
        'httpdocs/assets/css/messages-index.css',
        'httpdocs/assets/css/messages-thread.css',
        'httpdocs/assets/css/micro-interactions.css',
        'httpdocs/assets/css/mobile-accessibility-fixes.css',
        // 'httpdocs/assets/css/mobile-design-tokens.css', // EXCLUDED: Never purge design tokens
        'httpdocs/assets/css/mobile-loading-states.css',
        'httpdocs/assets/css/mobile-micro-interactions.css',
        'httpdocs/assets/css/mobile-nav-v2.css',
        'httpdocs/assets/css/mobile-search-overlay.css',
        'httpdocs/assets/css/mobile-select-sheet.css',
        'httpdocs/assets/css/mobile-sheets.css',
        'httpdocs/assets/css/modal-polish.css',
        'httpdocs/assets/css/modern-bundle-compiled.css',
        'httpdocs/assets/css/modern-bundle.css',
        'httpdocs/assets/css/modern-dashboard.css',
        'httpdocs/assets/css/modern-events-show.css',
        'httpdocs/assets/css/modern-experimental-banner.css',
        'httpdocs/assets/css/modern-groups-show.css',
        'httpdocs/assets/css/modern-header-emergency-fixes.css',
        'httpdocs/assets/css/modern-header-utilities.css',
        'httpdocs/assets/css/modern-onboarding.css',
        'httpdocs/assets/css/modern-primitives.css',
        'httpdocs/assets/css/modern-profile-show.css',
        'httpdocs/assets/css/modern-search-results.css',
        'httpdocs/assets/css/modern-settings-holographic.css',
        'httpdocs/assets/css/modern-settings.css',
        'httpdocs/assets/css/modern-volunteering-show.css',
        'httpdocs/assets/css/modern/components-library.css',
        'httpdocs/assets/css/modern/preview.css',
        // 'httpdocs/assets/css/moj-filter.css', // Excluded: contains GOV.UK Design System classes with ! in names (e.g., govuk-!-display-none)
        'httpdocs/assets/css/native-form-inputs.css',
        'httpdocs/assets/css/native-page-enter.css',
        'httpdocs/assets/css/nexus-civicone.css',
        'httpdocs/assets/css/nexus-groups.css',
        'httpdocs/assets/css/nexus-header-extracted.css',
        'httpdocs/assets/css/nexus-home.css',
        'httpdocs/assets/css/nexus-interactions.css',
        'httpdocs/assets/css/nexus-loading-fix.css',
        'httpdocs/assets/css/nexus-mobile.css',
        'httpdocs/assets/css/nexus-modern-footer.css',
        'httpdocs/assets/css/nexus-modern-header.css',
        'httpdocs/assets/css/nexus-native-nav-v2.css',
        'httpdocs/assets/css/nexus-performance-patch.css',
        'httpdocs/assets/css/nexus-phoenix.css',
        'httpdocs/assets/css/nexus-polish-temp.css',
        'httpdocs/assets/css/nexus-polish.css',
        'httpdocs/assets/css/nexus-premium-mega-menu.css',
        'httpdocs/assets/css/nexus-score.css',
        'httpdocs/assets/css/nexus-shared-transitions.css',
        'httpdocs/assets/css/noscript-fallbacks.css',
        'httpdocs/assets/css/notification-drawer.css',
        'httpdocs/assets/css/notifications.css',
        'httpdocs/assets/css/organizations.css',
        'httpdocs/assets/css/page-transitions.css',
        'httpdocs/assets/css/partials.css',
        'httpdocs/assets/css/polls.css',
        'httpdocs/assets/css/post-box-home.css',
        'httpdocs/assets/css/privacy-page.css',
        'httpdocs/assets/css/post-card.css',
        'httpdocs/assets/css/premium-dropdowns.css',
        'httpdocs/assets/css/premium-search.css',
        'httpdocs/assets/css/profile-edit.css',
        'httpdocs/assets/css/profile-holographic.css',
        'httpdocs/assets/css/pull-to-refresh.css',
        'httpdocs/assets/css/pwa-install-modal.css',
        'httpdocs/assets/css/resources.css',
        'httpdocs/assets/css/responsive-forms.css',
        'httpdocs/assets/css/responsive-tables.css',
        'httpdocs/assets/css/scattered-singles.css',
        'httpdocs/assets/css/scroll-fix-emergency.css',
        'httpdocs/assets/css/scroll-progress.css',
        'httpdocs/assets/css/search-results.css',
        'httpdocs/assets/css/share-compose.css',
        'httpdocs/assets/css/sidebar.css',
        'httpdocs/assets/css/social-interactions.css',
        'httpdocs/assets/css/static-pages.css',
        'httpdocs/assets/css/strategic-plan.css',
        'httpdocs/assets/css/terms-page.css',
        'httpdocs/assets/css/theme-transitions.css',
        'httpdocs/assets/css/toast-notifications.css',
        'httpdocs/assets/css/volunteering-critical.css',
        'httpdocs/assets/css/volunteering.css',
        'httpdocs/assets/css/wallet.css',
    ],

    // Output directory for purged CSS
    output: 'httpdocs/assets/css/purged/',

    // Safelist - classes to never remove
    safelist: {
        // Exact class names to keep
        standard: [
            // Dynamic state classes
            'active', 'open', 'closed', 'visible', 'hidden', 'show', 'hide',
            'loading', 'loaded', 'error', 'success', 'warning', 'info',
            'disabled', 'enabled', 'selected', 'checked', 'focused',
            'expanded', 'collapsed', 'animating', 'animated',
            'scrolled', 'sticky', 'fixed', 'ready', 'valid', 'invalid',
            'dark', 'light', 'mobile', 'desktop', 'tablet',

            // App state classes
            'verified-offline', 'hydrated', 'content-loaded',
            'no-ptr', 'chat-page', 'messages-fullscreen',
            'logged-in', 'user-is-admin',
            'nexus-home-page', 'nexus-skin-modern',
            'feed-loaded', 'page-loaded', 'fonts-loaded',
            'is-pwa', 'is-pwa-installed', 'is-native', 'is-native-app',
            'is-offline', 'pwa-installed', 'push-enabled',

            // Navigation states
            'drawer-open', 'nav-hidden', 'navigating', 'navigating-back',
            'hide-on-scroll', 'hiding', 'keyboard-open',
            'search-expanded', 'layout-switching',

            // Header states
            'nexus-header-compact', 'nexus-header-hidden', 'nexus-header-visible',
            'nexus-header-is-compact', 'nexus-header-is-hidden',
            'nexus-collapsing-header', 'back-nav',

            // Form and input states
            'form-row', 'form-group', 'form-label', 'form-input', 'form-note',
            'form-label-row', 'flex-1', 'flex-2',

            // Button base classes
            'btn', 'btn-primary', 'btn-secondary', 'btn-link', 'btn-sm', 'btn-lg',

            // Layout helpers
            'container', 'wrapper', 'content', 'main', 'section',
            'row', 'col', 'grid', 'flex',

            // Modern Primitives - Layout (Phase 7)
            'stack', 'cluster', 'sidebar',
            'container--narrow', 'container--wide',
            'stack--sm', 'stack--md', 'stack--lg', 'stack--xl',
            'cluster--start', 'cluster--center', 'cluster--end', 'cluster--between',
            'grid--2', 'grid--3', 'grid--4',
            'sidebar--right',

            // Modern Primitives - Accessibility
            'sr-only-focusable', 'focus-ring', 'no-focus-ring',

            // Visibility
            'sr-only', 'visually-hidden', 'invisible', 'opacity-0', 'opacity-100',
        ],

        // Patterns to keep (regex)
        deep: [
            // Keep all Font Awesome classes
            /^fa-/, /^fas$/, /^far$/, /^fab$/, /^fal$/, /^fad$/,

            // Keep all framework prefixed classes
            /^nexus-/, /^civic-/, /^civicone-/, /^fds-/,

            // Keep all module prefixed classes
            /^htb-/, /^fed-/, /^vol-/, /^group-/, /^goal-/,
            /^poll-/, /^resource-/, /^match-/, /^org-/, /^help-/,
            /^wallet-/, /^glass-/, /^admin-/,

            // Keep all feed/profile classes
            /^feed-/, /^composer-/, /^compose-/, /^sidebar-/,
            /^profile-/, /^badge/, /^avatar/,

            // Keep auth/login classes
            /^auth-/, /^login-/, /^register-/, /^password-/,

            // Keep biometric/security classes
            /^biometric-/,

            // Keep impersonation banner classes
            /^impersonation-/,

            // Keep holographic/calendar classes
            /^holo-/, /^calendar-/,

            // Keep skin/theme classes
            /^skin-/, /^theme-/,

            // Keep form classes
            /^form-/, /^input-/, /^select-/, /^checkbox-/, /^radio-/,

            // Keep button classes
            /^btn-/, /^button-/,

            // Keep blog classes
            /^blog-/, /^article-/, /^post-/,

            // Keep offline/status classes
            /^offline-/, /^online-/, /^status-/,

            // Keep GOV.UK Design System classes
            /^govuk-/, /^moj-/,

            // Keep all CSS variables and pseudo-elements
            /^--/, /::before/, /::after/,

            // Keep state patterns
            /^is-/, /^has-/, /hover/, /focus/, /active/,

            // Keep data attribute selectors
            /\[data-/,

            // Modern Primitives - Spacing utilities (Phase 7.1)
            /^gap-[1-8]$/,
            /^p-[1-8]$/,
            /^p[xy]-[2-6]$/,
            /^m[tb]-[0-8]$/,

            // Modern Primitives - Typography utilities (Phase 7.1)
            /^text-(xs|sm|base|lg|xl|2xl)$/,
            /^text-(primary|secondary|muted|accent|success|warning|danger)$/,
            /^font-(normal|medium|semibold|bold)$/,

            // Modern Primitives - Display/Flex utilities (Phase 7.1)
            /^flex-(row|col|wrap|nowrap|1|auto|none|grow|shrink-0)$/,
            /^items-(start|center|end|stretch)$/,
            /^justify-(start|center|end|between|around)$/,

            // Modern Primitives - Border radius utilities (Phase 7.1)
            /^rounded(-none|-sm|-md|-lg|-xl|-full)?$/,

            // Modern Primitives - Position utilities (Phase 7.1)
            /^(relative|absolute|fixed|sticky)$/,
            /^(top|right|bottom|left|inset)-0$/,
        ],
    },

    // Keep font-face declarations
    fontFace: true,

    // Keep keyframes
    keyframes: true,

    // Keep CSS variables
    variables: true,
};
