CREATE TABLE IF NOT EXISTS `job_templates` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id`       INT UNSIGNED NOT NULL,
  `user_id`         INT UNSIGNED NOT NULL COMMENT 'creator',
  `name`            VARCHAR(160) NOT NULL,
  `description`     TEXT NULL,
  `type`            ENUM('paid','volunteer','timebank') NOT NULL DEFAULT 'paid',
  `commitment`      ENUM('full_time','part_time','flexible','one_off') NOT NULL DEFAULT 'flexible',
  `category`        VARCHAR(100) NULL,
  `skills_required` VARCHAR(500) NULL,
  `is_remote`       TINYINT(1) NOT NULL DEFAULT 0,
  `salary_type`     ENUM('hourly','monthly','annual') NULL,
  `salary_currency` VARCHAR(10) NULL DEFAULT 'EUR',
  `salary_min`      DECIMAL(10,2) NULL,
  `salary_max`      DECIMAL(10,2) NULL,
  `hours_per_week`  DECIMAL(5,2) NULL,
  `time_credits`    DECIMAL(8,2) NULL,
  `benefits`        JSON NULL,
  `tagline`         VARCHAR(160) NULL,
  `is_public`       TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'shared with all tenant employers',
  `use_count`       INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_templates_tenant` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
