-- Phase 2 Migration Script: Fix Schema Mismatches
-- Generated by Antigravity
-- Date: 2026-01-10
-- -----------------------------------------------------------------------------
-- 1. Fix Table: permission_audit_log
-- -----------------------------------------------------------------------------
-- Add missing columns
ALTER TABLE `permission_audit_log`
ADD COLUMN IF NOT EXISTS `permission_name` varchar(100) DEFAULT NULL COMMENT 'Permission name at time of check',
    ADD COLUMN IF NOT EXISTS `resource_type` varchar(50) DEFAULT NULL COMMENT 'Type of resource accessed',
    ADD COLUMN IF NOT EXISTS `resource_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'ID of resource accessed',
    ADD COLUMN IF NOT EXISTS `result` enum('granted', 'denied') DEFAULT NULL COMMENT 'Result of permission check';
-- Modify existing columns to match source
ALTER TABLE `permission_audit_log`
MODIFY COLUMN `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `event_type` enum(
        'role_assigned',
        'role_revoked',
        'permission_granted',
        'permission_revoked',
        'permission_checked',
        'access_denied'
    ) NOT NULL,
    MODIFY COLUMN `user_id` int(11) NOT NULL COMMENT 'User affected by this event',
    MODIFY COLUMN `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address of requester',
    MODIFY COLUMN `user_agent` text DEFAULT NULL COMMENT 'Browser/client user agent';
-- -----------------------------------------------------------------------------
-- 2. Fix Table: role_permissions
-- -----------------------------------------------------------------------------
ALTER TABLE `role_permissions`
ADD COLUMN IF NOT EXISTS `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific',
    MODIFY COLUMN `granted_by` int(10) UNSIGNED DEFAULT NULL COMMENT 'User ID who granted this permission';
-- -----------------------------------------------------------------------------
-- 3. Fix Table: user_permissions
-- -----------------------------------------------------------------------------
ALTER TABLE `user_permissions`
ADD COLUMN IF NOT EXISTS `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific',
    MODIFY COLUMN `user_id` int(11) NOT NULL,
    MODIFY COLUMN `granted` tinyint(1) DEFAULT 1 COMMENT 'TRUE = grant, FALSE = revoke (override)',
    MODIFY COLUMN `granted_by` int(11) DEFAULT NULL COMMENT 'User ID who granted/revoked this permission',
    MODIFY COLUMN `reason` text DEFAULT NULL COMMENT 'Why this override was applied';
-- -----------------------------------------------------------------------------
-- 4. Fix Table: user_roles
-- -----------------------------------------------------------------------------
ALTER TABLE `user_roles`
ADD COLUMN IF NOT EXISTS `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific',
    MODIFY COLUMN `user_id` int(11) NOT NULL;
-- -----------------------------------------------------------------------------
-- 5. Fix Table: roles
-- -----------------------------------------------------------------------------
ALTER TABLE `roles`
MODIFY COLUMN `name` varchar(100) NOT NULL COMMENT 'Role identifier (e.g., gdpr_officer)',
    MODIFY COLUMN `display_name` varchar(150) NOT NULL COMMENT 'Human-readable role name',
    MODIFY COLUMN `description` text DEFAULT NULL COMMENT 'Role purpose and responsibilities',
    MODIFY COLUMN `level` int(10) UNSIGNED DEFAULT 0 COMMENT 'Role hierarchy level (higher = more privileges)',
    MODIFY COLUMN `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific';
-- -----------------------------------------------------------------------------
-- 6. Fix Table: permissions
-- -----------------------------------------------------------------------------
ALTER TABLE `permissions`
MODIFY COLUMN `name` varchar(100) NOT NULL COMMENT 'Permission identifier (e.g., users.delete)',
    MODIFY COLUMN `description` text DEFAULT NULL COMMENT 'Detailed description of what this permission allows',
    MODIFY COLUMN `category` varchar(50) NOT NULL COMMENT 'Permission category (users, gdpr, config, etc.)',
    MODIFY COLUMN `is_dangerous` tinyint(1) DEFAULT 0 COMMENT 'Requires extra confirmation (delete, ban, etc.)',
    MODIFY COLUMN `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific';