-- Migration Script Generated by Antigravity
-- Comparison between Local (source..sql) and Live (destination.sql)
-- Generated on: 2026-01-10
-- --------------------------------------------------------
-- 1. Missing Tables
-- --------------------------------------------------------
-- Missing Table: group_discussion_subscribers
CREATE TABLE IF NOT EXISTS `group_discussion_subscribers` (
    `id` int(11) NOT NULL,
    `discussion_id` int(11) NOT NULL,
    `user_id` int(11) NOT NULL,
    `created_at` datetime DEFAULT current_timestamp()
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- Missing Table: permissions
CREATE TABLE IF NOT EXISTS `permissions` (
    `id` int(10) UNSIGNED NOT NULL,
    `name` varchar(100) NOT NULL COMMENT 'Permission identifier (e.g., users.delete)',
    `display_name` varchar(150) NOT NULL COMMENT 'Human-readable name',
    `description` text DEFAULT NULL COMMENT 'Detailed description of what this permission allows',
    `category` varchar(50) NOT NULL COMMENT 'Permission category (users, gdpr, config, etc.)',
    `is_dangerous` tinyint(1) DEFAULT 0 COMMENT 'Requires extra confirmation (delete, ban, etc.)',
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Granular permissions for PBAC system';
-- Missing Table: permission_audit_log
CREATE TABLE IF NOT EXISTS `permission_audit_log` (
    `id` bigint(20) UNSIGNED NOT NULL,
    `event_type` enum(
        'role_assigned',
        'role_revoked',
        'permission_granted',
        'permission_revoked',
        'permission_checked',
        'access_denied'
    ) NOT NULL,
    `user_id` int(11) NOT NULL COMMENT 'User affected by this event',
    `actor_id` int(11) DEFAULT NULL COMMENT 'User who performed this action',
    `role_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'Role involved (if applicable)',
    `permission_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'Permission involved (if applicable)',
    `permission_name` varchar(100) DEFAULT NULL COMMENT 'Permission name at time of check',
    `resource_type` varchar(50) DEFAULT NULL COMMENT 'Type of resource accessed',
    `resource_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'ID of resource accessed',
    `result` enum('granted', 'denied') DEFAULT NULL COMMENT 'Result of permission check',
    `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address of requester',
    `user_agent` text DEFAULT NULL COMMENT 'Browser/client user agent',
    `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional context data' CHECK (json_valid(`metadata`)),
    `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Complete audit trail of all permission events (SOC 2, ISO 27001 requirement)';
-- Missing Table: roles
CREATE TABLE IF NOT EXISTS `roles` (
    `id` int(10) UNSIGNED NOT NULL,
    `name` varchar(100) NOT NULL COMMENT 'Role identifier (e.g., gdpr_officer)',
    `display_name` varchar(150) NOT NULL COMMENT 'Human-readable role name',
    `description` text DEFAULT NULL COMMENT 'Role purpose and responsibilities',
    `is_system` tinyint(1) DEFAULT 0 COMMENT 'System role (cannot be deleted)',
    `level` int(10) UNSIGNED DEFAULT 0 COMMENT 'Role hierarchy level (higher = more privileges)',
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Admin roles with specific permission sets';
-- Missing Table: role_permissions
CREATE TABLE IF NOT EXISTS `role_permissions` (
    `id` int(10) UNSIGNED NOT NULL,
    `role_id` int(10) UNSIGNED NOT NULL,
    `permission_id` int(10) UNSIGNED NOT NULL,
    `granted_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `granted_by` int(10) UNSIGNED DEFAULT NULL COMMENT 'User ID who granted this permission',
    `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Many-to-many mapping of roles to permissions';
-- Missing Table: user_layout_history
CREATE TABLE IF NOT EXISTS `user_layout_history` (
    `id` int(11) NOT NULL,
    `user_id` int(11) NOT NULL,
    `tenant_id` int(11) NOT NULL,
    `layout` varchar(50) NOT NULL,
    `switched_from` varchar(50) DEFAULT NULL,
    `switched_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `user_agent` text DEFAULT NULL,
    `ip_address` varchar(45) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Tracks user layout switching history for analytics';
-- Missing Table: user_permissions
CREATE TABLE IF NOT EXISTS `user_permissions` (
    `id` int(10) UNSIGNED NOT NULL,
    `user_id` int(11) NOT NULL,
    `permission_id` int(10) UNSIGNED NOT NULL,
    `granted` tinyint(1) DEFAULT 1 COMMENT 'TRUE = grant, FALSE = revoke (override)',
    `granted_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `granted_by` int(11) DEFAULT NULL COMMENT 'User ID who granted/revoked this permission',
    `reason` text DEFAULT NULL COMMENT 'Why this override was applied',
    `expires_at` timestamp NULL DEFAULT NULL COMMENT 'Optional expiration',
    `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Direct permission grants/revocations for specific users';
-- Missing Table: user_roles
CREATE TABLE IF NOT EXISTS `user_roles` (
    `id` int(10) UNSIGNED NOT NULL,
    `user_id` int(11) NOT NULL,
    `role_id` int(10) UNSIGNED NOT NULL,
    `assigned_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `assigned_by` int(11) DEFAULT NULL COMMENT 'User ID who assigned this role',
    `expires_at` timestamp NULL DEFAULT NULL COMMENT 'Optional expiration for temporary access',
    `tenant_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'NULL = global, otherwise tenant-specific'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Many-to-many mapping of users to roles';
-- --------------------------------------------------------
-- 2. Missing Views
-- --------------------------------------------------------
-- Missing View: user_effective_permissions
DROP TABLE IF EXISTS `user_effective_permissions`;
DROP VIEW IF EXISTS `user_effective_permissions`;
CREATE VIEW `user_effective_permissions` AS
SELECT DISTINCT `u`.`id` AS `user_id`,
    `p`.`id` AS `permission_id`,
    `p`.`name` AS `permission_name`,
    `p`.`category` AS `category`,
    CASE
        WHEN `up`.`granted` = 0 THEN 0
        WHEN `up`.`granted` = 1 THEN 1
        WHEN `rp`.`permission_id` is not null THEN 1
        ELSE 0
    END AS `has_permission`,
    CASE
        WHEN `up`.`id` is not null THEN 'direct'
        WHEN `rp`.`id` is not null THEN 'role'
        ELSE 'none'
    END AS `grant_source`
FROM (
        (
            (
                (
                    `users` `u`
                    left join `user_roles` `ur` on(
                        `u`.`id` = `ur`.`user_id`
                        and (
                            `ur`.`expires_at` is null
                            or `ur`.`expires_at` > current_timestamp()
                        )
                    )
                )
                left join `role_permissions` `rp` on(`ur`.`role_id` = `rp`.`role_id`)
            )
            left join `permissions` `p` on(
                `rp`.`permission_id` = `p`.`id`
                or `p`.`id` in (
                    select `user_permissions`.`permission_id`
                    from `user_permissions`
                    where `user_permissions`.`user_id` = `u`.`id`
                )
            )
        )
        left join `user_permissions` `up` on(
            `u`.`id` = `up`.`user_id`
            and `p`.`id` = `up`.`permission_id`
            and (
                `up`.`expires_at` is null
                or `up`.`expires_at` > current_timestamp()
            )
        )
    )
WHERE `p`.`id` is not null;
-- --------------------------------------------------------
-- 3. Missing Columns
-- --------------------------------------------------------
-- Missing Columns in 'users'
-- Note: 'is_admin' is deprecated but restored for compatibility if needed.
ALTER TABLE `users`
ADD COLUMN IF NOT EXISTS `preferred_layout` varchar(50) DEFAULT NULL COMMENT 'User-specific layout preference (modern, civicone, skeleton). NULL = use tenant default.',
    ADD COLUMN IF NOT EXISTS `is_admin` tinyint(1) DEFAULT 0 COMMENT 'Legacy admin flag (deprecated, use roles)',
    ADD COLUMN IF NOT EXISTS `max_permission_level` int(10) UNSIGNED DEFAULT 0 COMMENT 'Maximum permission level this user can grant',
    ADD COLUMN IF NOT EXISTS `permissions_last_updated` timestamp NULL DEFAULT NULL COMMENT 'Cache invalidation timestamp';