// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

/**
 * AG61 — Agent Proposals queue admin page.
 * ADMIN IS ENGLISH-ONLY — NO t() calls.
 */

import { useCallback, useEffect, useState } from 'react';
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  Chip,
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalHeader,
  Tab,
  Tabs,
  Textarea,
} from '@heroui/react';
import Bot from 'lucide-react/icons/bot';
import CheckCircle2 from 'lucide-react/icons/check-circle-2';
import XCircle from 'lucide-react/icons/x-circle';
import Edit3 from 'lucide-react/icons/edit-3';
import { usePageTitle } from '@/hooks';
import { useToast } from '@/contexts';
import { api } from '@/lib/api';

type ProposalStatus = 'pending' | 'approved' | 'rejected' | 'all';

interface AgentProposal {
  id: number;
  tenant_id: number;
  run_id: number;
  agent_definition_id: number | null;
  proposal_type: string;
  subject_user_id: number | null;
  target_user_id: number | null;
  proposal_data: Record<string, unknown>;
  reasoning: string | null;
  status: string;
  confidence_score: number | string | null;
  created_at: string;
}

export default function AgentProposalsPage() {
  usePageTitle('AI Agent Proposals');
  const toast = useToast();

  const [filter, setFilter] = useState<ProposalStatus>('pending');
  const [items, setItems] = useState<AgentProposal[]>([]);
  const [loading, setLoading] = useState(false);
  const [busyId, setBusyId] = useState<number | null>(null);

  const [rejecting, setRejecting] = useState<AgentProposal | null>(null);
  const [rejectNote, setRejectNote] = useState('');

  const [editing, setEditing] = useState<AgentProposal | null>(null);
  const [editPayload, setEditPayload] = useState('');

  const fetchItems = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get<{ items: AgentProposal[] }>(
        `/v2/admin/agents/proposals?status=${filter}&per_page=100`
      );
      setItems(res.data?.items ?? []);
    } catch {
      toast.error('Failed to load proposals');
    } finally {
      setLoading(false);
    }
  }, [filter, toast]);

  useEffect(() => {
    void fetchItems();
  }, [fetchItems]);

  const handleApprove = async (p: AgentProposal) => {
    setBusyId(p.id);
    try {
      await api.post(`/v2/admin/agents/proposals/${p.id}/approve`, {});
      toast.success('Proposal approved and executed');
      await fetchItems();
    } catch {
      toast.error('Failed to approve');
    } finally {
      setBusyId(null);
    }
  };

  const handleConfirmReject = async () => {
    if (!rejecting) return;
    setBusyId(rejecting.id);
    try {
      await api.post(`/v2/admin/agents/proposals/${rejecting.id}/reject`, { note: rejectNote });
      toast.success('Proposal rejected');
      setRejecting(null);
      setRejectNote('');
      await fetchItems();
    } catch {
      toast.error('Failed to reject');
    } finally {
      setBusyId(null);
    }
  };

  const openEdit = (p: AgentProposal) => {
    setEditing(p);
    setEditPayload(JSON.stringify(p.proposal_data ?? {}, null, 2));
  };

  const handleEditApprove = async () => {
    if (!editing) return;
    let parsed: unknown;
    try {
      parsed = JSON.parse(editPayload);
    } catch {
      toast.error('Edited payload is not valid JSON');
      return;
    }
    setBusyId(editing.id);
    try {
      await api.post(`/v2/admin/agents/proposals/${editing.id}/edit-approve`, {
        edited_payload: parsed,
      });
      toast.success('Proposal edited and approved');
      setEditing(null);
      await fetchItems();
    } catch {
      toast.error('Failed to edit and approve');
    } finally {
      setBusyId(null);
    }
  };

  const confidenceColor = (score: number | string | null): 'success' | 'warning' | 'danger' | 'default' => {
    const n = typeof score === 'string' ? parseFloat(score) : score ?? 0;
    if (n >= 0.75) return 'success';
    if (n >= 0.5) return 'warning';
    if (n > 0) return 'danger';
    return 'default';
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center gap-3">
        <Bot className="w-7 h-7 text-primary" />
        <div>
          <h1 className="text-2xl font-bold">Agent Proposals</h1>
          <p className="text-sm text-default-500">
            Review and approve proposals generated by autonomous agents.
          </p>
        </div>
      </div>

      <Tabs
        selectedKey={filter}
        onSelectionChange={(k) => setFilter(k as ProposalStatus)}
      >
        <Tab key="pending" title="Pending" />
        <Tab key="approved" title="Approved" />
        <Tab key="rejected" title="Rejected" />
        <Tab key="all" title="All" />
      </Tabs>

      {loading && <p className="text-default-500">Loading…</p>}

      {!loading && items.length === 0 && (
        <Card><CardBody className="text-default-500">No proposals.</CardBody></Card>
      )}

      <div className="space-y-4">
        {items.map((p) => (
          <Card key={p.id} className="border border-default-200">
            <CardHeader className="flex flex-wrap gap-2 justify-between items-start">
              <div className="flex flex-wrap gap-2 items-center">
                <Chip size="sm" variant="flat" color="primary">{p.proposal_type}</Chip>
                <Chip size="sm" variant="flat" color={confidenceColor(p.confidence_score)}>
                  Confidence: {(typeof p.confidence_score === 'string'
                    ? parseFloat(p.confidence_score)
                    : (p.confidence_score ?? 0)).toFixed(2)}
                </Chip>
                <Chip size="sm" variant="flat">Run #{p.run_id}</Chip>
                {p.subject_user_id && (
                  <Chip size="sm" variant="flat">Subject user: {p.subject_user_id}</Chip>
                )}
                {p.target_user_id && (
                  <Chip size="sm" variant="flat">Target user: {p.target_user_id}</Chip>
                )}
                <Chip size="sm" variant="flat" color={
                  p.status === 'approved' ? 'success' :
                  p.status === 'rejected' ? 'danger' : 'warning'
                }>{p.status}</Chip>
              </div>
              <span className="text-xs text-default-400">
                {new Date(p.created_at).toLocaleString()}
              </span>
            </CardHeader>
            <CardBody className="space-y-3">
              {p.reasoning && (
                <div>
                  <p className="text-xs font-semibold uppercase text-default-500">Reasoning</p>
                  <p className="text-sm">{p.reasoning}</p>
                </div>
              )}
              <div>
                <p className="text-xs font-semibold uppercase text-default-500">Payload</p>
                <pre className="text-xs bg-default-100 p-3 rounded-md overflow-x-auto">
                  {JSON.stringify(p.proposal_data, null, 2)}
                </pre>
              </div>
              {p.status === 'pending_review' && (
                <div className="flex gap-2 flex-wrap">
                  <Button
                    color="success"
                    variant="flat"
                    size="sm"
                    startContent={<CheckCircle2 className="w-4 h-4" />}
                    isLoading={busyId === p.id}
                    onPress={() => handleApprove(p)}
                  >
                    Approve
                  </Button>
                  <Button
                    color="primary"
                    variant="flat"
                    size="sm"
                    startContent={<Edit3 className="w-4 h-4" />}
                    onPress={() => openEdit(p)}
                  >
                    Edit & Approve
                  </Button>
                  <Button
                    color="danger"
                    variant="flat"
                    size="sm"
                    startContent={<XCircle className="w-4 h-4" />}
                    onPress={() => { setRejecting(p); setRejectNote(''); }}
                  >
                    Reject
                  </Button>
                </div>
              )}
            </CardBody>
          </Card>
        ))}
      </div>

      <Modal isOpen={!!rejecting} onClose={() => setRejecting(null)}>
        <ModalContent>
          <ModalHeader>Reject proposal #{rejecting?.id}</ModalHeader>
          <ModalBody>
            <Textarea
              label="Note (optional)"
              value={rejectNote}
              onValueChange={setRejectNote}
              minRows={3}
            />
          </ModalBody>
          <ModalFooter>
            <Button variant="flat" onPress={() => setRejecting(null)}>Cancel</Button>
            <Button color="danger" isLoading={busyId === rejecting?.id} onPress={handleConfirmReject}>
              Reject
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>

      <Modal isOpen={!!editing} onClose={() => setEditing(null)} size="2xl">
        <ModalContent>
          <ModalHeader>Edit & Approve proposal #{editing?.id}</ModalHeader>
          <ModalBody>
            <Textarea
              label="Payload (JSON)"
              value={editPayload}
              onValueChange={setEditPayload}
              minRows={12}
              className="font-mono text-xs"
            />
          </ModalBody>
          <ModalFooter>
            <Button variant="flat" onPress={() => setEditing(null)}>Cancel</Button>
            <Button color="success" isLoading={busyId === editing?.id} onPress={handleEditApprove}>
              Save & Approve
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </div>
  );
}
