import re
import os

def parse_sql_with_lines(filepath):
    schema = {}
    current_table = None
    table_lines = []
    
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            original_line = line
            line = line.strip()
            
            # Start of table
            create_match = re.match(r'^CREATE TABLE\s+`?(\w+)`?', line, re.IGNORECASE)
            if create_match:
                current_table = create_match.group(1)
                schema[current_table] = {'columns': {}, 'full_statement': [], 'is_view': False}
                if 'ALGORITHM=' in line or 'VIEW' in line:
                     # It might be a view, but usually dumps separate them.
                     pass
                schema[current_table]['full_statement'].append(original_line)
                continue
            
            if current_table:
                schema[current_table]['full_statement'].append(original_line)
                
                if line.startswith(') ENGINE='):
                    current_table = None
                    continue
                
                # Column parsing
                if line.startswith('`') and not ('KEY' in line or 'RINT' in line): # RINT for CONSTRAINT
                     col_match = re.match(r'^`(\w+)`\s+(.*),?$', line)
                     if col_match:
                         col_name = col_match.group(1)
                         col_def = col_match.group(2).rstrip(',')
                         schema[current_table]['columns'][col_name] = col_def

    return schema

def generate_migration(source_path, dest_path):
    source_schema = parse_sql_with_lines(source_path)
    dest_schema = parse_sql_with_lines(dest_path)
    
    migration_sql = []
    migration_sql.append("-- Migration Script Generated by Agent")
    migration_sql.append("-- Source: " + source_path)
    migration_sql.append("-- Destination: " + dest_path)
    migration_sql.append("\n-- --------------------------------------------------------")
    
    # Missing Tables
    missing_tables = []
    for table in source_schema:
        if table not in dest_schema:
            missing_tables.append(table)
            migration_sql.append(f"\n-- Missing Table: {table}")
            migration_sql.append("".join(source_schema[table]['full_statement']))
            
    # Missing Columns
    for table in source_schema:
        if table in dest_schema:
            for col, defn in source_schema[table]['columns'].items():
                if col not in dest_schema[table]['columns']:
                    migration_sql.append(f"\n-- Missing Column: {table}.{col}")
                    # Construct ALTER statement. Need to be careful about placement (AFTER x), but appending is safe usually.
                    # Use the definition from source
                    # Clean the definition (remove trailing comma if captured poorly, though regex handles it)
                    migration_sql.append(f"ALTER TABLE `{table}` ADD COLUMN `{col}` {defn};")
                    
    # Output
    print("\n".join(migration_sql))

if __name__ == "__main__":
    source = "c:/Home Directory/source..sql"
    dest = "c:/Home Directory/destination.sql"
    
    # Retry paths if needed
    if not os.path.exists(source) and os.path.exists("c:/Home Directory/source.sql"):
        source = "c:/Home Directory/source.sql"
        
    generate_migration(source, dest)
