#!/bin/bash
# =============================================================================
# Refresh trusted crawler IP ranges for nginx verification (Phase 4.1).
# =============================================================================
# Pulls the official IP-range JSON files published by major crawlers and
# converts them into an nginx `geo` include file. The `$nexus_is_verified_bot`
# variable in nginx.bluegreen.conf then resolves to "1" for any source IP in
# the union of these ranges.
#
# Reject vs flag: we DO NOT block spoofed UAs. We just log a `verified` field
# in the bot access log so admins can see "claimed Googlebot but failed IP
# verification" trends. Blocking is risky — alternative search engines, new
# crawlers, or IPv6 transitions can all produce false positives.
#
# Cron entry (weekly):
#   0 4 * * 1  root /opt/nexus-php/scripts/refresh-bot-ip-ranges.sh \
#                  >> /opt/nexus-php/logs/refresh-bot-ip-ranges.log 2>&1
#
# Output:
#   /etc/nginx/prerender-trusted-bot-ips.list  (in the nginx container)
# Format:
#   66.249.64.0/19 1;
#   2001:4860:4801::/48 1;
#
# Requires: curl, jq (or python3 fallback).
# =============================================================================

set -euo pipefail

NGINX_CONTAINER="${NGINX_CONTAINER:-nexus-react-prod}"
TARGET_PATH="${TARGET_PATH:-/etc/nginx/prerender-trusted-bot-ips.list}"

SOURCES=(
    # Google (Googlebot + Google-Extended)
    "google|https://developers.google.com/static/search/apis/ipranges/googlebot.json"
    "google-special|https://developers.google.com/static/search/apis/ipranges/special-crawlers.json"
    "google-user|https://developers.google.com/static/search/apis/ipranges/user-triggered-fetchers.json"
    # Bing
    "bing|https://www.bing.com/toolbox/bingbot.json"
    # DuckDuckGo
    "duckduckgo|https://duckduckgo.com/duckduckbot.json"
    # Apple
    "apple|https://search.developer.apple.com/applebot.json"
)

log() { echo "[$(date -Is)] $*"; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

OUT="$TMP/prerender-trusted-bot-ips.list"
echo "# Auto-generated by scripts/refresh-bot-ip-ranges.sh — do not edit." > "$OUT"
echo "# Refresh weekly via cron. Format: <cidr> 1;" >> "$OUT"

TOTAL=0
for SRC in "${SOURCES[@]}"; do
    LABEL="${SRC%%|*}"
    URL="${SRC#*|}"
    log "Fetching $LABEL from $URL"
    if ! curl -sSfL --max-time 30 "$URL" -o "$TMP/${LABEL}.json"; then
        log "WARN: failed to fetch $LABEL — skipping"
        continue
    fi

    # Extract ipv4Prefix / ipv6Prefix from each prefix entry.
    if command -v jq >/dev/null 2>&1; then
        COUNT=$(jq -r '.prefixes[]? | (.ipv4Prefix // .ipv6Prefix) | select(.)' "$TMP/${LABEL}.json" \
            | while read -r CIDR; do
                # Basic shape check.
                if [[ "$CIDR" =~ ^[0-9a-fA-F:.]+/[0-9]+$ ]]; then
                    echo "$CIDR 1;" >> "$OUT"
                fi
              done | wc -l)
    else
        COUNT=$(python3 -c "
import json, sys, re
data = json.load(open('$TMP/${LABEL}.json'))
out = []
for p in data.get('prefixes', []):
    v = p.get('ipv4Prefix') or p.get('ipv6Prefix')
    if v and re.match(r'^[0-9a-fA-F:.]+/[0-9]+$', v):
        out.append(v)
print('\n'.join(out))
" | while read -r CIDR; do
                echo "$CIDR 1;" >> "$OUT"
              done | wc -l)
    fi
    log "  $LABEL: added prefixes from feed"
    TOTAL=$((TOTAL + 1))
done

if [ "$TOTAL" -eq 0 ]; then
    log "ERROR: every feed failed; aborting without touching nginx"
    exit 1
fi

LINE_COUNT=$(wc -l < "$OUT")
log "Generated $OUT ($LINE_COUNT lines from $TOTAL feeds)"

if ! docker ps --format '{{.Names}}' | grep -q "^${NGINX_CONTAINER}$"; then
    log "WARN: $NGINX_CONTAINER not running; skipping copy + reload"
    exit 0
fi

docker cp "$OUT" "${NGINX_CONTAINER}:${TARGET_PATH}"

if docker exec "$NGINX_CONTAINER" nginx -t >/dev/null 2>&1; then
    docker exec "$NGINX_CONTAINER" nginx -s reload >/dev/null 2>&1 || true
    log "Applied; nginx reloaded"
else
    log "WARN: nginx -t failed after update; manual investigation required"
    exit 1
fi
