/**
 * Legacy Service Worker — Self-Unregister Shim
 *
 * The old PHP frontend service worker has been replaced by the React app's
 * Workbox-based SW (generated by vite-plugin-pwa). This file exists only to
 * clean up old registrations in users' browsers that still reference /sw.js.
 *
 * What it does:
 * 1. Immediately activates (skipWaiting + claim) so it takes over from the old SW
 * 2. Deletes all old caches (nexus-v*, etc.)
 * 3. Unregisters itself so the browser no longer has a SW at this scope
 * 4. Reloads active tabs to pick up the clean state
 */

// Activate immediately — don't wait for old tabs to close
self.addEventListener('install', () => self.skipWaiting());

self.addEventListener('activate', async (event) => {
  event.waitUntil(
    (async () => {
      // 1. Delete all old caches
      const cacheNames = await caches.keys();
      await Promise.all(cacheNames.map((name) => caches.delete(name)));

      // 2. Take control of all clients
      await self.clients.claim();

      // 3. Unregister this service worker
      const registration = await self.registration.unregister();
      console.info('[NEXUS] Legacy SW unregistered:', registration);

      // 4. Reload all open tabs so they start fresh
      const clients = await self.clients.matchAll({ type: 'window' });
      for (const client of clients) {
        if (client.url && 'navigate' in client) {
          client.navigate(client.url);
        }
      }
    })()
  );
});

// Pass through all fetch requests — don't cache anything
self.addEventListener('fetch', () => {
  // No-op: let browser handle normally
});
