// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

/**
 * PlatformPrivacyPage — Platform-level Privacy Policy for Project NEXUS.
 *
 * Covers data processing at the platform infrastructure level only.
 * Community Operators maintain their own privacy policies for community-level data.
 */

import { Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { usePageTitle } from '@/hooks/usePageTitle';
import {
  PlatformLegalPage,
  type PlatformLegalSection,
} from '@/components/legal/PlatformLegalPage';

const sections: PlatformLegalSection[] = [
  /* ── 1. Introduction ── */
  {
    id: 'introduction',
    title: 'Introduction',
    content: (
      <>
        <p>
          This Platform Privacy Policy explains how <strong>Project NEXUS</strong>, operated by
          Jasper Ford (the "Platform Provider"), collects, uses, stores, and protects personal data
          at the <strong>platform infrastructure level</strong>. It applies to all users who access
          services delivered through the Project NEXUS platform.
        </p>
        <p>
          This policy covers only the data processing that occurs at the platform infrastructure
          layer — server logs, error monitoring, security events, and similar operational data. It
          does <strong>not</strong> govern how your Community Operator collects or uses your personal
          data within their community.
        </p>
        <p>
          Your Community Operator (the organisation that runs your timebank or community) maintains
          their own privacy policy, which covers community-level data such as your profile
          information, messages, exchanges, and other content you create within the community. You
          should review your Community Operator's privacy policy for details on how they handle your
          data.
        </p>
        <p>
          If you have questions about this Platform Privacy Policy, you can reach us through{' '}
          <a
            href="https://project-nexus.ie"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            project-nexus.ie
          </a>
          .
        </p>
      </>
    ),
  },

  /* ── 2. Data Controller vs Data Processor ── */
  {
    id: 'controller-processor',
    title: 'Data Controller vs Data Processor',
    content: (
      <>
        <p>
          Under the General Data Protection Regulation (GDPR), different parties bear different
          responsibilities depending on their role in data processing. Within the Project NEXUS
          ecosystem, responsibilities are divided as follows:
        </p>
        <p>
          <strong>Community Member Data</strong> — For personal data that community members provide
          within a community (profiles, messages, exchange records, and similar content), the
          Platform acts as a <strong>Data Processor</strong>. The Community Operator who runs your
          timebank or community is the <strong>Data Controller</strong>. This means your Community
          Operator determines the purposes and means of processing your personal data, while the
          Platform processes it only on their behalf and in accordance with their instructions.
        </p>
        <p>
          <strong>Platform Infrastructure Data</strong> — For data generated by the platform
          infrastructure itself (server logs, error reports, performance metrics, and security event
          records), the Platform Provider (Jasper Ford) is the <strong>Data Controller</strong>. This
          data is collected to ensure the security, stability, and proper functioning of the
          platform.
        </p>
        <p>
          Community Operators are independently responsible for their own GDPR compliance, including
          maintaining a lawful basis for processing, publishing their own privacy policies, and
          responding to data subject requests concerning community-level data. The Platform does not
          make decisions about how community-level personal data is used — those decisions rest with
          the Community Operator.
        </p>
      </>
    ),
  },

  /* ── 3. Data We Collect at Platform Level ── */
  {
    id: 'data-collected',
    title: 'Data We Collect at Platform Level',
    content: (
      <>
        <p>
          At the platform infrastructure level, we collect and process the following categories of
          data:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Server access logs</strong> — IP addresses, timestamps, HTTP request methods and
            URLs, response status codes, and referrer headers. These logs are essential for security
            monitoring, abuse prevention, and diagnosing technical issues.
          </li>
          <li>
            <strong>Error reports via Sentry</strong> — When errors occur, our error tracking service
            (Sentry) captures stack traces, browser information, operating system details, and
            anonymised user context. This data helps us identify and resolve bugs quickly.
          </li>
          <li>
            <strong>Performance monitoring metrics</strong> — Response times, server resource
            utilisation, and application performance indicators. These metrics are used in aggregate
            to maintain platform reliability.
          </li>
          <li>
            <strong>Aggregate usage analytics</strong> — We collect aggregate, non-identifying usage
            statistics (such as total page views or feature adoption rates) to improve the platform.
            We do not perform individual user tracking at the platform level.
          </li>
          <li>
            <strong>Security event logs</strong> — Records of rate-limiting actions, failed
            authentication attempts, suspicious request patterns, and other security-relevant events.
            These logs are critical for protecting the platform and its users from malicious
            activity.
          </li>
        </ul>
        <p>
          <strong>Note:</strong> Member profile data, messages, time credit exchanges, group
          memberships, event registrations, and other community-level content are processed by the
          Platform on behalf of your Community Operator. The collection and use of that data is
          governed by your Community Operator's privacy policy, not this document.
        </p>
      </>
    ),
  },

  /* ── 4. Legal Basis for Processing ── */
  {
    id: 'legal-basis',
    title: 'Legal Basis for Processing',
    content: (
      <>
        <p>
          We process platform-level personal data under the following legal bases as defined by the
          GDPR:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Legitimate interests (Article 6(1)(f) GDPR)</strong> — We have a legitimate
            interest in maintaining the security, stability, and integrity of the platform. This
            includes monitoring for and preventing abuse, detecting security threats, diagnosing
            errors, and ensuring the platform performs reliably for all users and Community
            Operators. We have assessed that these interests are not overridden by the rights and
            freedoms of data subjects, given the limited scope and operational nature of the data
            processed.
          </li>
          <li>
            <strong>Contract performance (Article 6(1)(b) GDPR)</strong> — Processing is necessary
            for the provision of platform infrastructure services to Community Operators and, by
            extension, to the members of those communities. Without this processing, we would be
            unable to deliver the platform services.
          </li>
          <li>
            <strong>Legal obligation (Article 6(1)(c) GDPR)</strong> — In certain circumstances, we
            may be required to process or retain data to comply with applicable laws, regulations,
            or lawful requests from law enforcement authorities.
          </li>
        </ul>
      </>
    ),
  },

  /* ── 5. Data Sharing ── */
  {
    id: 'data-sharing',
    title: 'Data Sharing',
    content: (
      <>
        <p>
          We share platform-level data with the following third-party service providers, each of
          which is necessary for the operation, security, or reliability of the platform:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Sentry (Functional Software Inc.)</strong> — Error tracking and application
            monitoring. Sentry receives error reports, stack traces, and anonymised user context to
            help us diagnose and fix issues. Data is stored in Sentry's EU data region.
          </li>
          <li>
            <strong>Cloudflare Inc.</strong> — Content delivery network (CDN), distributed denial of
            service (DDoS) protection, web application firewall (WAF), and SSL/TLS termination.
            Cloudflare processes request metadata (IP addresses, headers, URLs) to protect the
            platform from malicious traffic.
          </li>
          <li>
            <strong>Pusher Ltd.</strong> — Real-time WebSocket communications. Pusher facilitates
            instant messaging, notifications, and live updates within the platform. Connection
            metadata is processed to maintain real-time channels.
          </li>
          <li>
            <strong>Microsoft Azure</strong> — Cloud hosting infrastructure. All primary platform
            services are hosted on Microsoft Azure within the EU region. Azure provides the compute,
            storage, and networking resources on which the platform operates.
          </li>
        </ul>
        <p>
          We do <strong>not</strong> sell personal data to third parties. We will never monetise user
          data through advertising, data brokerage, or any other commercial arrangement.
        </p>
        <p>
          Data may be disclosed to third parties if we are required to do so by law, regulation, or
          valid legal process, or if disclosure is reasonably necessary to protect the rights,
          property, or safety of the Platform Provider, Community Operators, users, or the public.
        </p>
      </>
    ),
  },

  /* ── 6. International Data Transfers ── */
  {
    id: 'international-transfers',
    title: 'International Data Transfers',
    content: (
      <>
        <p>
          Our primary hosting infrastructure is located in the <strong>EU region</strong> on
          Microsoft Azure. We make every effort to keep personal data within the European Economic
          Area (EEA).
        </p>
        <p>
          However, some of our sub-processors may process limited data outside the EU. In
          particular:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Cloudflare</strong> operates a global network of data centres. While traffic is
            typically routed to the nearest point of presence, request metadata may be processed in
            non-EU locations as part of Cloudflare's security and CDN services.
          </li>
          <li>
            <strong>Pusher</strong> may process WebSocket connection data in data centres outside the
            EU to ensure low-latency real-time communications.
          </li>
        </ul>
        <p>
          Where personal data is transferred outside the EEA, we ensure that appropriate safeguards
          are in place in accordance with GDPR Chapter V. These safeguards include the European
          Commission's Standard Contractual Clauses (SCCs), adequacy decisions where applicable, or
          other recognised transfer mechanisms. We regularly review the data protection practices of
          our sub-processors to ensure continued compliance.
        </p>
      </>
    ),
  },

  /* ── 7. Data Retention ── */
  {
    id: 'retention',
    title: 'Data Retention',
    content: (
      <>
        <p>
          We retain platform-level data only for as long as necessary to fulfil the purposes
          described in this policy. Specific retention periods are as follows:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Server access logs:</strong> 90 days. After this period, logs are permanently
            deleted.
          </li>
          <li>
            <strong>Sentry error reports:</strong> 90 days. Error data is automatically purged by
            Sentry after this retention window.
          </li>
          <li>
            <strong>Security event logs:</strong> 12 months. A longer retention period is necessary
            to support security investigations and identify patterns of abuse over time.
          </li>
          <li>
            <strong>Performance metrics:</strong> 30 days. These metrics are aggregated and contain
            no personally identifiable information.
          </li>
          <li>
            <strong>Community member data:</strong> Retained for as long as the Community is active
            on the platform. Upon community closure or deactivation, data is handled in accordance
            with the Community Operator's instructions and any applicable data processing agreement.
          </li>
        </ul>
        <p>
          When retention periods expire, data is securely deleted or irreversibly anonymised. We do
          not retain data longer than necessary for the stated purposes.
        </p>
      </>
    ),
  },

  /* ── 8. Your Rights Under GDPR ── */
  {
    id: 'your-rights',
    title: 'Your Rights Under GDPR',
    content: (
      <>
        <p>
          Under the General Data Protection Regulation, you have the following rights in relation to
          your personal data:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Right of access (Article 15)</strong> — You have the right to obtain
            confirmation as to whether your personal data is being processed and, if so, to access
            that data along with information about the processing.
          </li>
          <li>
            <strong>Right to rectification (Article 16)</strong> — You have the right to request
            correction of inaccurate personal data and to have incomplete data completed.
          </li>
          <li>
            <strong>Right to erasure (Article 17)</strong> — You have the right to request the
            deletion of your personal data in certain circumstances, such as when the data is no
            longer necessary for the purpose for which it was collected.
          </li>
          <li>
            <strong>Right to restriction of processing (Article 18)</strong> — You have the right to
            request that processing of your personal data be restricted in certain situations, for
            example while the accuracy of the data is being verified.
          </li>
          <li>
            <strong>Right to data portability (Article 20)</strong> — You have the right to receive
            your personal data in a structured, commonly used, and machine-readable format, and to
            transmit that data to another controller.
          </li>
          <li>
            <strong>Right to object (Article 21)</strong> — You have the right to object to
            processing based on legitimate interests. We will cease processing unless we can
            demonstrate compelling legitimate grounds that override your interests, rights, and
            freedoms.
          </li>
        </ul>
        <p>
          <strong>For platform-level data</strong> (server logs, error reports, security events):
          Contact the Platform Provider (see the Contact section below) to exercise your rights.
        </p>
        <p>
          <strong>For community-level data</strong> (your profile, messages, exchanges, and other
          content within your community): Contact your Community Operator directly. As Data
          Controller, they are responsible for handling your data subject requests.
        </p>
        <p>
          You also have the right to lodge a complaint with a supervisory authority. The relevant
          authority for the Platform Provider is the Data Protection Commission (Ireland), or you may
          contact the supervisory authority in the EU Member State of your habitual residence or
          place of work.
        </p>
      </>
    ),
  },

  /* ── 9. Security Measures ── */
  {
    id: 'security',
    title: 'Security Measures',
    content: (
      <>
        <p>
          We implement appropriate technical and organisational measures to protect personal data
          against unauthorised access, alteration, disclosure, or destruction. These measures
          include:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Encryption in transit</strong> — All data transmitted between users, the
            platform, and third-party services is protected by SSL/TLS encryption. HTTPS is enforced
            across all platform domains.
          </li>
          <li>
            <strong>Web Application Firewall and DDoS protection</strong> — Cloudflare's WAF and
            DDoS mitigation services protect the platform from malicious traffic, injection attacks,
            and volumetric attacks.
          </li>
          <li>
            <strong>Database encryption at rest</strong> — Databases storing personal data are
            encrypted at rest using industry-standard encryption algorithms.
          </li>
          <li>
            <strong>Access controls and least privilege</strong> — Access to production systems,
            databases, and infrastructure is strictly limited to authorised personnel and follows the
            principle of least privilege.
          </li>
          <li>
            <strong>Security monitoring and vulnerability assessment</strong> — We conduct regular
            security monitoring, review access logs, and assess the platform for vulnerabilities. Error
            tracking via Sentry enables rapid detection and response to application-level issues.
          </li>
          <li>
            <strong>Rate limiting on sensitive endpoints</strong> — Authentication endpoints, API
            routes, and other sensitive operations are protected by rate limiting to prevent brute
            force attacks and abuse.
          </li>
          <li>
            <strong>Multi-tenant data isolation</strong> — The platform enforces strict data
            isolation between communities (tenants). Each community's data is logically separated so
            that one community cannot access another community's data.
          </li>
        </ul>
        <p>
          While we take security seriously and implement robust protections, no system is entirely
          immune to risk. We continuously review and improve our security measures in response to
          evolving threats.
        </p>
      </>
    ),
  },

  /* ── 10. Contact ── */
  {
    id: 'contact',
    title: 'Contact',
    content: (
      <>
        <p>
          If you have questions about this Platform Privacy Policy or wish to exercise your rights
          regarding platform-level data, you can reach the Platform Provider through the following
          channels:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Platform Provider:</strong> Jasper Ford
          </li>
          <li>
            <strong>Website:</strong>{' '}
            <a
              href="https://project-nexus.ie"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 hover:underline"
            >
              project-nexus.ie
            </a>
          </li>
        </ul>
        <p>
          For privacy queries specific to your community — such as questions about how your profile
          data, messages, or exchange records are handled — please contact your Community Operator
          directly. As the Data Controller for community-level data, they are best placed to assist
          you.
        </p>
        <p>
          If you are not satisfied with our response, or if you believe that your data protection
          rights have been infringed, you have the right to lodge a complaint with the relevant
          supervisory authority:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Data Protection Commission (Ireland)</strong>
            <br />
            21 Fitzwilliam Square South, Dublin 2, D02 RD28, Ireland
            <br />
            <a
              href="https://www.dataprotection.ie"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 hover:underline"
            >
              www.dataprotection.ie
            </a>
          </li>
        </ul>
        <p>
          You may also contact the supervisory authority in the EU Member State of your habitual
          residence or place of work if different from Ireland.
        </p>
      </>
    ),
  },
];

export function PlatformPrivacyPage() {
  const { t } = useTranslation('legal');
  usePageTitle(t('platform_privacy.page_title'));
  return (
    <PlatformLegalPage
      title={t('platform_privacy.title')}
      subtitle={t('platform_privacy.subtitle')}
      icon={Shield}
      effectiveDate="1 March 2026"
      sections={sections}
      crossLinks={[
        { label: t('platform_privacy.link_terms'), to: '/platform/terms' },
        { label: t('platform_privacy.link_disclaimer'), to: '/platform/disclaimer' },
      ]}
    />
  );
}

export default PlatformPrivacyPage;
