// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

import { AlertTriangle } from 'lucide-react';
import { usePageTitle } from '@/hooks/usePageTitle';
import {
  PlatformLegalPage,
  type PlatformLegalSection,
} from '@/components/legal/PlatformLegalPage';

const sections: PlatformLegalSection[] = [
  /* ── 1. No Warranty ── */
  {
    id: 'no-warranty',
    title: 'No Warranty',
    content: (
      <>
        <p>
          <strong>
            THE SOFTWARE IS PROVIDED UNDER THE AGPL-3.0-OR-LATER LICENSE
            &ldquo;AS IS&rdquo;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
            NON-INFRINGEMENT.
          </strong>
        </p>
        <p>
          <strong>
            THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
            APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE
            COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM
            &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
            OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
            OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE
            RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.
            SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
            NECESSARY SERVICING, REPAIR OR CORRECTION.
          </strong>
        </p>
        <p>
          Without limiting the generality of the foregoing, the Platform
          provider makes no warranties or representations regarding:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Fitness of the Platform for any particular purpose, including but
            not limited to community timebanking, service exchange, volunteer
            coordination, or any other use;
          </li>
          <li>
            Uninterrupted, timely, secure, or error-free operation of the
            Platform;
          </li>
          <li>
            The accuracy, reliability, completeness, or currentness of any
            information, content, data, or materials made available through or
            generated by the Platform;
          </li>
          <li>
            Compliance of the Platform with any particular legal, regulatory, or
            industry framework in your jurisdiction or any other jurisdiction;
          </li>
          <li>
            That defects in the Platform will be corrected within any particular
            timeframe, or at all.
          </li>
        </ul>
        <p>
          The Platform provider makes no representations about the suitability
          of this software for community timebanking or any other purpose. Your
          use of the Platform is entirely at your own risk.
        </p>
      </>
    ),
  },

  /* ── 2. No Legal, Financial, or Regulatory Advice ── */
  {
    id: 'no-advice',
    title: 'No Legal, Financial, or Regulatory Advice',
    content: (
      <>
        <p>
          The Platform does <strong>NOT</strong> provide, and nothing on the
          Platform should be construed as, legal, financial, tax, accounting,
          investment, or regulatory advice of any kind.
        </p>
        <p>
          <strong>
            Time Credits are NOT legal tender, currency, money, financial
            instruments, securities, commodities, tokens, vouchers, or any
            form of stored value.
          </strong>{' '}
          Time Credits are a unit of account used solely within individual
          Communities to facilitate the recording of service exchanges between
          Members. Time Credits have no monetary value whatsoever and cannot
          be converted to, sold for, redeemed for, or exchanged for money,
          cryptocurrency, goods, or any other form of consideration outside
          the Platform.
        </p>
        <p>
          Users and Community Operators should seek independent professional
          advice regarding any legal, tax, regulatory, insurance, or
          compliance matters arising from their use of the Platform or their
          participation in timebanking activities. This includes, without
          limitation:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Tax obligations or reporting requirements that may apply to
            timebanking activities in your jurisdiction;
          </li>
          <li>
            Insurance requirements for services offered or exchanged between
            Members;
          </li>
          <li>
            Regulatory permits, licences, or registrations that may be required
            for certain types of services;
          </li>
          <li>
            Employment law implications, including but not limited to minimum
            wage legislation, worker classification, and labour regulations;
          </li>
          <li>
            Data protection and privacy obligations applicable to Community
            Operators who process personal data of their Members.
          </li>
        </ul>
        <p>
          The Platform provider makes no representations whatsoever about the
          legality, permissibility, or regulatory treatment of timebanking in
          any jurisdiction worldwide.
        </p>
      </>
    ),
  },

  /* ── 3. Community Operator Independence ── */
  {
    id: 'operator-independence',
    title: 'Community Operator Independence',
    content: (
      <>
        <p>
          Each Community on the Platform is <strong>INDEPENDENTLY</strong>{' '}
          operated by its own Operator. The relationship between the Platform
          provider and each Operator is strictly that of a technology licensor
          and licensee (under the AGPL-3.0-or-later licence). There is no
          partnership, joint venture, agency, franchise, employment, or
          fiduciary relationship between the Platform provider and any
          Operator.
        </p>
        <p>
          <strong>
            The Platform provider does NOT, and has never undertaken to:
          </strong>
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Employ, supervise, direct, or manage any Operator;</li>
          <li>
            Train, certify, accredit, endorse, or recommend any Operator;
          </li>
          <li>
            Vet, screen, audit, inspect, or evaluate any Operator or their
            operations;
          </li>
          <li>
            Insure, indemnify, or provide any financial guarantee for any
            Operator;
          </li>
          <li>
            Control, approve, or review any Operator&apos;s decisions regarding
            their Community.
          </li>
        </ul>
        <p>
          Operators make all decisions regarding their Community&apos;s
          policies, rules, membership criteria and vetting procedures, content
          moderation standards, dispute resolution processes, data handling
          practices, safeguarding measures, and day-to-day operations.
        </p>
        <p>
          <strong>
            The Platform provider has NO control over and accepts NO
            responsibility for any Operator&apos;s decisions, actions,
            omissions, negligence, or compliance status with applicable laws
            and regulations.
          </strong>
        </p>
        <p>
          The appearance of a Community on the Platform does not constitute an
          endorsement, recommendation, certification, warranty, or guarantee of
          any kind by the Platform provider. No inference of affiliation,
          approval, or quality assurance should be drawn from a
          Community&apos;s presence on the Platform.
        </p>
      </>
    ),
  },

  /* ── 4. Member Interactions ── */
  {
    id: 'member-interactions',
    title: 'Member Interactions',
    content: (
      <>
        <p>
          The Platform facilitates connections between Members but is{' '}
          <strong>NOT</strong> a party to any exchange, transaction, agreement,
          arrangement, or interaction between Members. All exchanges of
          services between Members are undertaken entirely at the Members&apos;
          own risk.
        </p>
        <p>
          <strong>The Platform does NOT:</strong>
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Guarantee, warrant, or make any representation regarding the
            quality, safety, legality, suitability, timeliness, or fitness of
            any service offered, listed, or exchanged via the Platform;
          </li>
          <li>
            Verify, assess, test, or certify the skills, qualifications,
            competence, credentials, licences, insurance status, or
            professional standing of any Member;
          </li>
          <li>
            Mediate, adjudicate, arbitrate, or resolve disputes between
            Members — dispute resolution is the sole responsibility of the
            Community Operator;
          </li>
          <li>
            Provide insurance, indemnity, compensation, or any form of
            financial protection for any loss, injury, damage, or
            dissatisfaction arising from exchanges between Members;
          </li>
          <li>
            Assume any duty of care, fiduciary obligation, or supervisory
            responsibility toward any Member.
          </li>
        </ul>
        <p>
          Members are strongly advised to exercise their own independent
          judgement, conduct their own due diligence, and take all
          appropriate precautions before, during, and after any service
          exchange. This includes, without limitation, verifying
          qualifications, checking references, confirming insurance coverage,
          and assessing risks relevant to the nature of the service being
          exchanged.
        </p>
      </>
    ),
  },

  /* ── 5. Content and Uploads ── */
  {
    id: 'content-uploads',
    title: 'Content and Uploads',
    content: (
      <>
        <p>
          Users and Operators are <strong>solely responsible</strong> for all
          content they upload, post, publish, transmit, or otherwise make
          available via the Platform, including but not limited to text,
          images, photographs, profile information, listings, event
          descriptions, blog posts, comments, messages, and any other
          user-generated content.
        </p>
        <p>
          <strong>
            The Platform does NOT pre-screen, review, approve, edit, verify,
            or endorse user-generated content.
          </strong>{' '}
          The presence of content on the Platform does not indicate that the
          Platform provider has reviewed it or that it is accurate, lawful,
          non-infringing, or appropriate.
        </p>
        <p>
          Content moderation within each Community is the responsibility of
          the Community Operator. The Platform provider may, but is under no
          obligation to, remove content that violates platform-level terms.
          The Platform provider has no obligation to monitor, review, or
          screen any content.
        </p>
        <p>
          By uploading content to the Platform, you represent and warrant that:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            You have the legal right and authority to upload, publish, and
            distribute the content;
          </li>
          <li>
            The content does not infringe, misappropriate, or violate any
            third party&apos;s intellectual property rights, privacy rights,
            publicity rights, or any other proprietary rights;
          </li>
          <li>
            The content is not defamatory, obscene, harassing, threatening,
            fraudulent, or otherwise unlawful;
          </li>
          <li>
            The content does not contain viruses, malware, or other harmful
            code.
          </li>
        </ul>
        <p>
          The Platform provider accepts no liability for any content uploaded,
          posted, or transmitted by users or Operators.
        </p>
      </>
    ),
  },

  /* ── 6. Identity Verification ── */
  {
    id: 'identity-verification',
    title: 'Identity Verification',
    content: (
      <>
        <p>
          <strong>
            The Platform does NOT verify the identity of any user, Member, or
            Operator.
          </strong>{' '}
          While the Platform provides tools such as email verification,
          administrative approval workflows, and profile management features
          that Operators <em>may</em> choose to use, the decision to use
          these tools and the adequacy of any verification process are the
          sole responsibility of the Operator.
        </p>
        <p>
          <strong>
            The Platform makes NO representation, warranty, or guarantee that
            any user is who they claim to be.
          </strong>{' '}
          Display names, profile photographs, biographical information,
          qualifications, and any other self-reported data have not been
          independently verified by the Platform provider unless explicitly
          stated otherwise.
        </p>
        <p>
          Operators are solely responsible for implementing appropriate
          vetting, screening, and safeguarding procedures as required by their
          jurisdiction and the nature of services being exchanged within their
          Community. This includes, without limitation:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Criminal background checks (e.g., Garda vetting, DBS checks,
            police clearance certificates) where required or advisable;
          </li>
          <li>
            Reference checks and character assessments for Members offering
            services to vulnerable persons;
          </li>
          <li>
            Verification of professional qualifications, licences, or
            certifications where services require specialised training;
          </li>
          <li>
            Age verification for Members and compliance with child protection
            legislation;
          </li>
          <li>
            Any other safeguarding measures mandated by applicable law or
            best practice in the Operator&apos;s jurisdiction.
          </li>
        </ul>
        <p>
          <strong>
            The Platform provider accepts NO liability for any harm, loss,
            injury, damage, or adverse consequence arising from inadequate or
            absent identity verification by an Operator or from the actions
            of any user whose identity has not been verified.
          </strong>
        </p>
      </>
    ),
  },

  /* ── 7. Third-Party Services ── */
  {
    id: 'third-party',
    title: 'Third-Party Services',
    content: (
      <>
        <p>
          The Platform integrates with, relies upon, or links to various
          third-party services and platforms. These include, but are not
          limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong>Cloudflare</strong> — content delivery network (CDN),
            DDoS protection, DNS, and web application firewall services;
          </li>
          <li>
            <strong>Sentry</strong> — application error monitoring and
            performance tracking;
          </li>
          <li>
            <strong>Pusher</strong> — real-time WebSocket communications for
            messaging and notifications;
          </li>
          <li>
            <strong>Google Maps</strong> — location and mapping services for
            events and member locations;
          </li>
          <li>
            <strong>Firebase Cloud Messaging (FCM)</strong> — push notification
            delivery for mobile and web applications;
          </li>
          <li>
            <strong>OpenAI</strong> — AI-powered features including chat
            assistance;
          </li>
          <li>
            Other services as may be added, changed, or removed from time to
            time without prior notice.
          </li>
        </ul>
        <p>
          The Platform provider is <strong>NOT</strong> responsible for the
          availability, uptime, reliability, accuracy, security, privacy
          practices, data handling, or terms of service of any third-party
          service. Use of third-party services is subject to those
          services&apos; own terms of service, privacy policies, and
          acceptable use policies, which you should review independently.
        </p>
        <p>
          The Platform provider makes no warranty, representation, or
          guarantee regarding:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Continued availability or compatibility of any third-party
            service with the Platform;
          </li>
          <li>
            The security or privacy of data processed by third-party services;
          </li>
          <li>
            The accuracy of information provided by third-party services;
          </li>
          <li>
            That third-party services will not be discontinued, modified, or
            made subject to additional terms or fees.
          </li>
        </ul>
        <p>
          If a third-party service experiences an outage, security incident,
          or discontinuation, the Platform provider shall not be liable for
          any resulting disruption to the Platform or loss of data.
        </p>
      </>
    ),
  },

  /* ── 8. Limitation of Liability ── */
  {
    id: 'limitation-of-liability',
    title: 'Limitation of Liability',
    content: (
      <>
        <p>
          <strong>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
            SHALL THE PLATFORM PROVIDER, ITS OFFICERS, DIRECTORS, EMPLOYEES,
            AGENTS, CONTRIBUTORS, LICENSORS, OR AFFILIATES BE LIABLE FOR ANY:
          </strong>
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong>Direct, indirect, incidental, special, consequential,
            exemplary, or punitive damages</strong> of any kind;
          </li>
          <li>
            <strong>Loss of profits, revenue, data, goodwill, business
            opportunity, anticipated savings, or other intangible losses;</strong>
          </li>
          <li>
            <strong>Cost of procurement of substitute goods or
            services;</strong>
          </li>
          <li>
            <strong>Personal injury or property damage</strong> arising from
            your use of the Platform or from interactions between Members;
          </li>
          <li>
            <strong>Any unauthorised access to, use of, alteration of, or
            destruction of</strong> your data, transmissions, or content;
          </li>
        </ul>
        <p>
          <strong>
            ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE
            PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING
            NEGLIGENCE), STRICT LIABILITY, STATUTE, OR ANY OTHER LEGAL
            THEORY.
          </strong>
        </p>
        <p>
          This limitation applies regardless of whether the Platform provider
          has been advised of, knew of, or should have known of the
          possibility of such damages. This limitation applies to all causes
          of action in the aggregate, including but not limited to breach of
          contract, breach of warranty, negligence, strict liability,
          misrepresentation, and any other tort.
        </p>
        <p>
          Some jurisdictions do not allow the exclusion or limitation of
          certain warranties, or the exclusion or limitation of liability for
          incidental, consequential, or certain other damages. In such
          jurisdictions, the Platform provider&apos;s liability shall be
          limited to the minimum extent permitted by applicable law.
        </p>
        <p>
          <strong>
            NOTHING IN THIS DISCLAIMER SHALL EXCLUDE OR LIMIT LIABILITY FOR:
          </strong>
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Death or personal injury caused by the Platform provider&apos;s
            negligence;
          </li>
          <li>Fraud or fraudulent misrepresentation;</li>
          <li>
            Any other liability that cannot be excluded or limited under
            applicable law.
          </li>
        </ul>
        <p>
          If, notwithstanding the foregoing limitations, the Platform provider
          is found liable to you for any damage or loss arising from or
          related to your use of the Platform, the Platform provider&apos;s
          total aggregate liability shall in no event exceed the amount of one
          euro (&euro;1.00), or the minimum amount permitted by applicable law
          if greater.
        </p>
      </>
    ),
  },
];

export function PlatformDisclaimerPage() {
  usePageTitle('Platform Disclaimer');
  return (
    <PlatformLegalPage
      title="Platform Disclaimer"
      subtitle="Important disclaimers and liability limitations for the Project NEXUS platform"
      icon={AlertTriangle}
      effectiveDate="1 March 2026"
      sections={sections}
      crossLinks={[
        { label: 'Platform Terms of Service', to: '/platform/terms' },
        { label: 'Platform Privacy Policy', to: '/platform/privacy' },
      ]}
    />
  );
}

export default PlatformDisclaimerPage;
